source 'https://github.com/CocoaPods/Specs.git'

# Cannot use frameworks until min deployment set to 8.0
# use_frameworks!

target 'Operative_Example', :exclusive => true do
  pod "Operative", :path => "../"
end

target 'Operative_Tests', :exclusive => true do
  pod "Operative", :path => "../"
end
